# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /logs/*.log
# - type: log
#   enabled: true
#   paths:
#     - /var/lib/docker/containers/*/*.log

# filebeat.config:
#   modules:
#     path: /modules.d/*.yml
#     reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.image: owasp/modsecurity-crs
          config:
            type: container
            paths:
              - /var/lib/docker/containers/${data.docker.container.id}/*.log

setup.kibana:
  host: "localhost:5601"
  username: "elastic"
  password: "changeme"
 
output.logstash:
  hosts: ["localhost:5044"]
  ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-beats.crt"]



#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true

#processors:
#- add_cloud_metadata: ~

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
